#!/bin/sh

case $BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send "🖥 CPU module " "\- Shows CPU usage.
- Click to show intensive processes.
- Middle click to open htop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

cat <(grep 'cpu ' /proc/stat) <(sleep .01 && grep 'cpu ' /proc/stat) | awk -v RS="" '{printf ":%5.1f%%", ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)}'
#top -b -n2 -p 1 | fgrep "Cpu(s)" | tail -1 | awk -F'id,' -v prefix="$prefix" '{ split($1, vs, ","); v=vs[length(vs)]; sub("%", "", v); printf ": %s%.1f%%\n", prefix, 100 - v }'
