#!/bin/sh

case $BUTTON in
	1) notify-send -h string:x-dunst-stack-tag:mem_block " Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send -h string:x-dunst-stack-tag:mem_block " Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs.
- Middle click to open htop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

free -h --si | sed -n '2{p;q}' | awk '{printf ": %s/%s", $3, $2}'
