#!/bin/sh

# Displays number of upgradeable packages.
# For this to work, have a `pacman -Sy` command run in the background as a
# cronjob every so often as root. This script will then read those packages.
# When clicked, it will run an upgrade via pacman.
#
# Add the following text as a file in /usr/share/libalpm/hooks/statusbar.hook:
#
# [Trigger]
# Operation = Upgrade
# Type = Package
# Target = *
#
# [Action]
# Description = Updating statusbar...
# When = PostTransaction
# Exec = /usr/bin/pkill -RTMIN+8 dwmblocks # Or i3blocks if using i3.

case $BUTTON in
	2) setsid -w -f "$TERMINAL" -e yay ;;
	1) notify-send -h string:x-dunst-stack-tag:pac_block "$(/usr/bin/pacman -Qu)" ;;
	3) notify-send -h string:x-dunst-stack-tag:pac_block " Upgrade module" ": number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

pacman -Qu | grep -Fcv "[ignored]" | sed "s/^/:/;s/^0$//g" | awk 'END { if ($0=="") print ":0"; else print}'

