#!/bin/sh

# Prints the current volume or  if muted.

case $BUTTON in
	2) setsid -f "$TERMINAL" -c pulsemixer -e pulsemixer ;;
	1) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send -h string:x-dunst-stack-tag:vol_block "📢 Volume module" "\- Shows volume ,  if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --get-mute) = true ] && echo  && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon=""
fi

printf "%s:%3d%%" $icon $vol
